# Generated by Django 4.2.2 on 2023-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(max_length=1000)),
                ('employee_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='email_/images')),
            ],
        ),
    ]
