# Generated by Django 4.2.2 on 2023-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.IntegerField()),
                ('message', models.TextField()),
                ('mail_sent_date', models.DateField()),
                ('mail_type', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='event_type',
        ),
    ]
