# Generated by Django 4.2.2 on 2023-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_', '0002_mail_logs_remove_employee_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.AddField(
            model_name='template',
            name='message',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.CharField(default='demo', max_length=255),
            preserve_default=False,
        ),
    ]
